## 1. Нарисуйте график функции y = x^2 на интервале от -5 до 5.

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
x = np.arange(-5, 5, 0.05)
y = x ** 2
plt.plot(x,y)
plt.xlabel('x առանցք')
plt.ylabel('y առանցք')
plt.title('x^2')
plt.show()

## 2. Создайте массив размером 5x5, заполненный случайными числами от 0 до 1, и нарисуйте его с помощью функции imshow из библиотеки Matplotlib.

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
x = np.random.rand(5,5)
print(x)
plt.imshow(x)
# print(x) added to show the values in this array.

## 3. Найдите интеграл функции $y = e^{-x^2}$ на интервале от 0 до 1 с помощью функции quad из библиотеки SciPy.

In [3]:
import scipy.integrate as sp
import math
b = lambda x: pow(math.e, -x**2)
a = sp.quad(b, 0, 1)
print(a)

(0.7468241328124271, 8.291413475940725e-15)


## 4. Нарисуйте график функции $y = \sin(x)$ и её производной $y' = \cos(x)$ на интервале от 0 до 2π.

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import math
x1 = np.arange(0, 2*math.pi, 0.15)
y1 = np.sin(x1)
plt.plot(x1,y1)
plt.xlabel('x առանցք')
plt.ylabel('y առանցք')
plt.title('sin(x)')
plt.show()
x2 = np.arange(0, 2*math.pi, 0.15)
y2 = np.cos(x1)
plt.plot(x2,y2)
plt.xlabel('x առանցք')
plt.ylabel('y առանցք')
plt.title('cos(x)')
plt.show()

## 5. Найдите корни уравнения $x^3 - 3x^2 + 3x - 1 = 0$ с помощью функции roots из библиотеки NumPy.

In [12]:
import scipy.optimize as sco
x = [-100,100]
y = lambda x: x**3-3*x**2+3*x-1
a = sco.fsolve(y,x)
print(a)
#Im used fsolve from scipy.optimize instead of roots from numpy. 
#Also I set the range for x values.

[0.99999672 1.00000322]


## 6. Найдите определитель матрицы A = [[1, 2], [3, 4]] с помощью функции det из библиотеки NumPy.

In [13]:
import numpy.linalg as nl
A = [[1,2],[3,4]]
y = nl.det(A)
print(y)

-2.0000000000000004


## 7. Нарисуйте график функции $y = e^{-x}\cos(2\pi x)$ на интервале от 0 до 5.

## 8. Создайте массив размером 3x3, заполненный случайными целыми числами от 0 до 9, и отсортируйте его по возрастанию по каждой строке с помощью функции sort из библиотеки NumPy.

In [14]:
import numpy as np
x = np.random.rand(3,3)*100//10
y = np.sort(x)
print(y)

[[6. 7. 8.]
 [4. 4. 8.]
 [1. 6. 6.]]


## 9. Найдите скалярное произведение векторов a = [1, 2, 3] и b = [4, 5, 6] с помощью функции dot из библиотеки NumPy.

In [15]:
import numpy as np
a = [1,2,3]
b = [4,5,6]
y = np.dot(a,b)
print(y)

32


## 10. Найдите производную функции $y = x^3 - 2x^2 + x$ в точке x = 2 с помощью функции derivative из библиотеки SciPy.

In [7]:
import sympy as sy


c:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\sympy\core\function.py:1238: SymPyDeprecationWarning: 

The string fallback in sympify() is deprecated.

To explicitly convert the string form of an object, use
sympify(str(obj)). To add define sympify behavior on custom
objects, use sympy.core.sympify.converter or define obj._sympy_
(see the sympify() docstring).

sympify() performed the string fallback resulting in the following string:

'<function <lambda> at 0x0000015F1E8913A0>'

See https://docs.sympy.org/latest/explanation/active-deprecations.html#deprecated-sympify-string-fallback
for details.

This has been deprecated since SymPy version 1.6. It
will be removed in a future version of SymPy.

  expr = sympify(expr)


SympifyError: Sympify of expression 'could not parse '<function <lambda> at 0x0000015F1E8913A0>'' failed, because of exception being raised:
SyntaxError: invalid syntax (<string>, line 1)